const TypographyTheme = () =>{
  return `
    <div class="ui-typography ui-component">
      <h2 class="ui-lead py-2 h2 border-bottom border-2">Typography</h2>
      <div class="list">      
        <h1>The quick brown fox jumps over the lazy dog</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tempus erat velit, nec porta purus sollicitudin a. Sed dapibus ultrices turpis, sit amet pharetra urna bibendum ac. Phasellus aliquam elit sed imperdiet accumsan. Sed ac lectus a orci efficitur mattis. Integer <a href="#">ullamcorper maximus</a> ex. Ut id volutpat mauris. Nullam condimentum enim ac enim pellentesque sollicitudin. Aliquam tincidunt vulputate massa, et facilisis mi pretium sed. Nulla vitae tincidunt tellus. Vivamus ultrices sem leo. Ut turpis mauris, vestibulum eget consectetur ac, consequat eget velit.</p>
        <p class="mb-3">Fusce tincidunt arcu metus, nec fringilla enim pellentesque eu. Integer sed justo ornare, fermentum dui ut, placerat velit. Pellentesque eu augue ultrices, dignissim nisl quis, placerat turpis. Praesent vitae facilisis velit. Praesent convallis turpis ut commodo tincidunt. Nullam nec urna et massa imperdiet consequat eget in ligula. Integer dictum dui id libero blandit, vel mollis libero justo.</p>
        <h2>The quick brown fox jumps over the lazy dog</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tempus erat velit, nec porta purus sollicitudin a. Sed dapibus ultrices turpis, sit amet pharetra urna bibendum ac. Phasellus aliquam elit sed imperdiet accumsan. Sed ac lectus a orci efficitur mattis. Integer <strong>ullamcorper maximus</strong> ex. Ut id volutpat mauris. Nullam condimentum enim ac enim pellentesque sollicitudin. Aliquam tincidunt vulputate massa, et facilisis mi pretium sed. Nulla vitae tincidunt tellus. Vivamus ultrices sem leo. Ut turpis mauris, vestibulum eget consectetur ac, consequat eget velit.</p>
        <p class="mb-3">Fusce tincidunt arcu metus, nec fringilla enim pellentesque eu. Integer sed justo ornare, fermentum dui ut, placerat velit. Pellentesque eu augue ultrices, dignissim nisl quis, placerat turpis. Praesent vitae facilisis velit. Praesent convallis turpis ut commodo tincidunt. Nullam nec urna et massa imperdiet consequat eget in ligula. Integer dictum dui id libero blandit, vel mollis libero justo.</p>
        <h3>The quick brown fox jumps over the lazy dog</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tempus erat velit, nec porta purus sollicitudin a. Sed dapibus ultrices turpis, sit amet pharetra urna bibendum ac. Phasellus aliquam elit sed imperdiet accumsan. Sed ac lectus a orci efficitur mattis. Integer <em class="bg-accent color-light">ullamcorper maximus</em> ex. Ut id volutpat mauris. Nullam condimentum enim ac enim pellentesque sollicitudin. Aliquam tincidunt vulputate massa, et facilisis mi pretium sed. Nulla vitae tincidunt tellus. Vivamus ultrices sem leo. Ut turpis mauris, vestibulum eget consectetur ac, consequat eget velit.</p>
        <p class="mb-3">Fusce tincidunt arcu metus, nec fringilla enim pellentesque eu. Integer sed justo ornare, fermentum dui ut, placerat velit. Pellentesque eu augue ultrices, dignissim nisl quis, placerat turpis. Praesent vitae facilisis velit. Praesent convallis turpis ut commodo tincidunt. Nullam nec urna et massa imperdiet consequat eget in ligula. Integer dictum dui id libero blandit, vel mollis libero justo.</p>
        <h4>The quick brown fox jumps over the lazy dog</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tempus erat velit, nec porta purus sollicitudin a. Sed dapibus ultrices turpis, sit amet pharetra urna bibendum ac. Phasellus aliquam elit sed imperdiet accumsan. Sed ac lectus a orci efficitur mattis. Integer <span class="small link">ullamcorper maximus</span> ex. Ut id volutpat mauris. Nullam condimentum enim ac enim pellentesque sollicitudin. Aliquam tincidunt vulputate massa, et facilisis mi pretium sed. Nulla vitae tincidunt tellus. Vivamus ultrices sem leo. Ut turpis mauris, vestibulum eget consectetur ac, consequat eget velit.</p>
        <p class="mb-3">Fusce tincidunt arcu metus, nec fringilla enim pellentesque eu. Integer sed justo ornare, fermentum dui ut, placerat velit. Pellentesque eu augue ultrices, dignissim nisl quis, placerat turpis. Praesent vitae facilisis velit. Praesent convallis turpis ut commodo tincidunt. Nullam nec urna et massa imperdiet consequat eget in ligula. Integer dictum dui id libero blandit, vel mollis libero justo.</p>
        <h5>The quick brown fox jumps over the lazy dog</h5>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tempus erat velit, nec porta purus sollicitudin a. Sed dapibus ultrices turpis, sit amet pharetra urna bibendum ac. Phasellus aliquam elit sed imperdiet accumsan. Sed ac lectus a orci efficitur mattis. Integer <span class="text-uppercase weight-thin color-error">ullamcorper maximus</span> ex. Ut id volutpat mauris. Nullam condimentum enim ac enim pellentesque sollicitudin. Aliquam tincidunt vulputate massa, et facilisis mi pretium sed. Nulla vitae tincidunt tellus. Vivamus ultrices sem leo. Ut turpis mauris, vestibulum eget consectetur ac, consequat eget velit.</p>
        <p class="mb-3">Fusce tincidunt arcu metus, nec fringilla enim pellentesque eu. Integer sed justo ornare, fermentum dui ut, placerat velit. Pellentesque eu augue ultrices, dignissim nisl quis, placerat turpis. Praesent vitae facilisis velit. Praesent convallis turpis ut commodo tincidunt. Nullam nec urna et massa imperdiet consequat eget in ligula. Integer dictum dui id libero blandit, vel mollis libero justo.</p>
        <h6>The quick brown fox jumps over the lazy dog</h6>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tempus erat velit, nec porta purus sollicitudin a. Sed dapibus ultrices turpis, sit amet pharetra urna bibendum ac. Phasellus aliquam elit sed imperdiet accumsan. Sed ac lectus a orci efficitur mattis. Integer <span class="bg-neutral-light color-success font-normal weight-superbold px-1">ullamcorper maximus</span> ex. Ut id volutpat mauris. Nullam condimentum enim ac enim pellentesque sollicitudin. Aliquam tincidunt vulputate massa, et facilisis mi pretium sed. Nulla vitae tincidunt tellus. Vivamus ultrices sem leo. Ut turpis mauris, vestibulum eget consectetur ac, consequat eget velit.</p>
        <p>Fusce tincidunt arcu metus, nec fringilla enim pellentesque eu. Integer sed justo ornare, fermentum dui ut, placerat velit. Pellentesque eu augue ultrices, dignissim nisl quis, placerat turpis. Praesent vitae facilisis velit. Praesent convallis turpis ut commodo tincidunt. Nullam nec urna et massa imperdiet consequat eget in ligula. Integer dictum dui id libero blandit, vel mollis libero justo.</p>        
      </div>      
    </div>
`
}

export default TypographyTheme